#!/usr/bin/env bash

# Wake up (wake up)
# Grab a brush and put a little make-up
# Hide the scars to fade away the shake-up
# Why'd you leave the keys upon the table?
# Here you go create another fable
# You wanted to
# Grab a brush and put a little makeup
# You wanted to
# Hide the scars to fade away the shake-up
# You wanted to
# Why'd you leave the keys upon the table?
# You wanted to
# I don't think you trust
# In
# my
# self-righteous suicide
# I
# cry
# when angels deserve to
# Die

devices=$(awk '$3 == "*enabled" {print $1}' /proc/acpi/wakeup)

for dev in $devices; do
    echo "$dev" | sudo tee /proc/acpi/wakeup > /dev/null
done
