#!/bin/bash
set -e

# Install a launchd LaunchAgent that forces every external display into
# 8-bit RGB Full instead of macOS's default YCbCr 4:2:2 Limited negotiation.
# macOS often picks 4:2:2 to preserve 10-bit color depth at high refresh
# rates (e.g. 1440p144 over DP 1.2), but halved chroma resolution makes
# desktop text look fuzzy. BetterDisplay's `connectionMode` override is
# the only way to fix this on Apple Silicon — System Settings has no UI.
#
# Architecture:
#   - Uses BetterDisplay's `--type=Display` batch selector, which targets
#     every natively-negotiated external display in a single CLI call.
#     Built-in laptop panels have no queryable connectionMode and are
#     filtered out automatically — no explicit "is it built-in?" check
#     needed.
#   - Discovery phase (up to 10s): wait for `get` to return any mode info.
#     If empty after the grace window, no externals are connected and we
#     exit clean — important so the agent doesn't burn CPU on laptop-only
#     setups.
#   - Apply phase (up to 15s): `set` once; verify; retry every 0.5s until
#     every reported mode line contains "RGB Full".
#
# LaunchAgent triggers (in order of responsiveness):
#   1. LaunchEvents + IOKit matching on `IODisplay` — fires the agent
#      whenever a display service is attached. This is the event-driven
#      replug recovery (typically < 3s after replug, dominated by macOS
#      re-negotiation time).
#   2. RunAtLoad — fires on user login.
#   3. StartInterval=15 — polling safety net for cases where IOKit
#      matching doesn't fire (sleep/wake renegotiation, certain Apple
#      Silicon edge cases). Helper exits in ~100ms when already correct,
#      so per-poll cost is negligible.
#
# Requires the `betterdisplay` cask (installed by setup/brew/betterdisplay.sh).

LABEL="com.adrian.betterdisplay-rgb"
MODE="bpc:8+range:full+encoding:rgb"
TARGET_MARKER="RGB Full"
CLI="/opt/homebrew/bin/betterdisplaycli"

AGENT_DIR="$HOME/Library/LaunchAgents"
SUPPORT_DIR="$HOME/Library/Application Support/betterdisplay-rgb"
LOG_DIR="$HOME/Library/Logs"
PLIST="$AGENT_DIR/$LABEL.plist"
HELPER="$SUPPORT_DIR/apply.sh"
LOG="$LOG_DIR/betterdisplay-rgb.log"

mkdir -p "$AGENT_DIR" "$SUPPORT_DIR" "$LOG_DIR"

cat > "$HELPER" <<HELPER_EOF
#!/bin/bash
# Generated by setup/tweak/betterdisplay-rgb.sh — do not edit; rerun the installer.

CLI="$CLI"
MODE="$MODE"
TARGET="$TARGET_MARKER"
DISCOVER_TIMEOUT=10
APPLY_TIMEOUT=15

[ -x "\$CLI" ] || exit 0

ts() { date '+%Y-%m-%d %H:%M:%S'; }

# Returns 0 if \$1 is non-empty and every line contains \$TARGET.
all_target() {
    [ -n "\$1" ] || return 1
    ! printf '%s\\n' "\$1" | grep -vF "\$TARGET" | grep -q .
}

# Phase 1: wait for any queryable external display to appear. Empty result
# means BetterDisplay isn't up yet, or there are no external displays at all.
deadline=\$(( \$(date +%s) + DISCOVER_TIMEOUT ))
modes=""
while [ "\$(date +%s)" -lt "\$deadline" ]; do
    modes=\$("\$CLI" get --type=Display --connectionMode 2>/dev/null)
    [ -n "\$modes" ] && break
    sleep 0.5
done

[ -n "\$modes" ] || exit 0

# Happy path: every queryable display already in target mode.
all_target "\$modes" && exit 0

# Phase 2: batch-apply across all matched displays, verify, retry until done.
deadline=\$(( \$(date +%s) + APPLY_TIMEOUT ))
while [ "\$(date +%s)" -lt "\$deadline" ]; do
    "\$CLI" set --type=Display --connectionMode="\$MODE" >/dev/null 2>&1 || true
    sleep 0.5
    modes=\$("\$CLI" get --type=Display --connectionMode 2>/dev/null)
    all_target "\$modes" && exit 0
done

echo "[\$(ts)] not every display reached \$TARGET within \${APPLY_TIMEOUT}s; last state: \$modes" >&2
exit 1
HELPER_EOF

chmod +x "$HELPER"

cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>$HELPER</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>StartInterval</key>
    <integer>15</integer>
    <key>LaunchEvents</key>
    <dict>
        <key>com.apple.iokit.matching</key>
        <dict>
            <key>$LABEL.display-attached</key>
            <dict>
                <key>IOProviderClass</key>
                <string>IODisplay</string>
            </dict>
        </dict>
    </dict>
    <key>StandardOutPath</key>
    <string>$LOG</string>
    <key>StandardErrorPath</key>
    <string>$LOG</string>
</dict>
</plist>
EOF

launchctl bootout "gui/$UID" "$PLIST" 2>/dev/null || true
launchctl bootstrap "gui/$UID" "$PLIST"

echo "Installed $LABEL"
echo "  plist:   $PLIST"
echo "  helper:  $HELPER"
echo "  log:     $LOG"
echo "  mode:    $MODE (applied to every queryable external display)"
echo "  triggers: login + IODisplay attach + every 15s safety net"
