#!/bin/bash
set -e

# Install a launchd LaunchAgent that runs the `update` workflow (brew + zinit)
# at most once an hour, polling every minute and catching up after sleep or
# transient failure. See openspec/changes/add-update-schedule/design.md.

LABEL="com.adrian.update"
SUPPORT="$HOME/Library/Application Support/update-schedule"
LOG_DIR="$HOME/Library/Logs"
STAMP_DIR="$HOME/.cache/update-schedule"
AGENT_DIR="$HOME/Library/LaunchAgents"
CHECK="$SUPPORT/check.sh"
PLIST="$AGENT_DIR/$LABEL.plist"
LOG="$LOG_DIR/update-schedule.log"

mkdir -p "$SUPPORT" "$LOG_DIR" "$STAMP_DIR" "$AGENT_DIR"

cat > "$CHECK" <<'CHECKEOF'
#!/bin/bash
# Generated by setup/tweak/update-schedule.sh — do not edit; rerun the installer.

STAMP="$HOME/.cache/update-schedule"
# Lock lives in the private stamp dir, not a predictable world-writable /tmp
# path (avoids symlink/squat games and cross-user collisions).
LOCK="$STAMP/pid"
BREW=/opt/homebrew/bin/brew
ZSH=/bin/zsh
WINDOW=3600   # last_success must be older than 1h to trigger
RETRY=600     # last_attempt must be older than 10min to retry after failure

# Don't let an unattended `brew upgrade` touch self-updating GUI casks (Docker,
# Chrome, ...). Recent Homebrew upgrades `auto_updates true` casks by default,
# which quits the running app via an AppleScript quit event and then needs sudo
# to swap the bundle -- headless, sudo fails, the upgrade never completes, and
# it retries every $RETRY seconds, quitting the app (e.g. Docker Desktop -> the
# Linux VM + daemon) on every run. These casks update themselves; brew should
# leave them alone. https://docs.brew.sh/Manpage (search NO_UPGRADE_AUTO_UPDATES)
export HOMEBREW_NO_UPGRADE_AUTO_UPDATES_CASKS=1

if [ -f "$LOCK" ] && kill -0 "$(cat "$LOCK" 2>/dev/null)" 2>/dev/null; then
  exit 0
fi
echo $$ > "$LOCK"
trap 'rm -f "$LOCK"' EXIT INT TERM

age() {
  if [ -f "$1" ]; then
    echo $(( $(date +%s) - $(stat -f %m "$1") ))
  else
    echo 999999999
  fi
}

[ "$(age "$STAMP/last_success")" -ge "$WINDOW" ] || exit 0
[ "$(age "$STAMP/last_attempt")" -ge "$RETRY"  ] || exit 0

ts() { date '+%Y-%m-%d %H:%M:%S'; }
echo "[$(ts)] update-schedule: starting run"
touch "$STAMP/last_attempt"

"$BREW" update \
  && "$BREW" upgrade \
  && "$BREW" cleanup \
  && "$ZSH" -ic 'zinit update --all' \
  && touch "$STAMP/last_success" \
  && echo "[$(ts)] update-schedule: success"
CHECKEOF

chmod +x "$CHECK"

cat > "$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>$LABEL</string>
    <key>ProgramArguments</key>
    <array>
        <string>$CHECK</string>
    </array>
    <key>StartInterval</key>
    <integer>60</integer>
    <key>RunAtLoad</key>
    <true/>
    <key>StandardOutPath</key>
    <string>$LOG</string>
    <key>StandardErrorPath</key>
    <string>$LOG</string>
</dict>
</plist>
EOF

launchctl bootout "gui/$UID" "$PLIST" 2>/dev/null || true
launchctl bootstrap "gui/$UID" "$PLIST"

echo "Installed $LABEL"
echo "  plist:  $PLIST"
echo "  script: $CHECK"
echo "  log:    $LOG"
